# Chap. 5

## Chap. 5-1

### 5-1-2

In [1]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt

%precision 3

'%.3f'

> `import numpy.random as random`は，`random`モジュールとのバッティングを避けるため，実行していない。

### 5-2-1

In [2]:
sample_array = np.arange(10)

In [3]:
print(f'sample_array = {sample_array}')
sample_array_slice = sample_array[0:5]
print(f'sample_array_slice = {sample_array_slice}')

sample_array = [0 1 2 3 4 5 6 7 8 9]
sample_array_slice = [0 1 2 3 4]


In [4]:
sample_array_slice[0:3] = 10
print(f'sample_array_slice = {sample_array_slice}')
print(f'sample_array = {sample_array}')

sample_array_slice = [10 10 10  3  4]
sample_array = [10 10 10  3  4  5  6  7  8  9]


> `sample_array_slice`は`sample_array[0:5]`を(メモリ)参照しているだけなので，`sample_array_slice`の成分を**弄る**と`sample_array`も同様に**弄られる**。**別物の**配列（リストも）を作るには，**np.copy関数(copy関数←リストの場合)**をつかう（5-2-1-1をみよ）。

#### 5-2-1-1

In [5]:
sample_array_copy = np.copy(sample_array)
print(f'sample_array_copy = {sample_array_copy}')

sample_array_copy = [10 10 10  3  4  5  6  7  8  9]


In [6]:
sample_array_copy[0:3] = 20
print(f'sample_array_copy = {sample_array_copy}')
print(f'sample_array = {sample_array}')

sample_array_copy = [20 20 20  3  4  5  6  7  8  9]
sample_array = [10 10 10  3  4  5  6  7  8  9]


#### 5-2-1-2

In [13]:
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
np.random.seed(0)
data = np.random.randn(5,5)

print(f'sample_name = {sample_names}')
print(f'data = \n{data}')

sample_name = ['a' 'b' 'c' 'd' 'a']
data = 
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [14]:
print(f'sample_names == \"a\" → {sample_names == "a"}')

sample_names == "a" → [ True False False False  True]


In [15]:
print(f'data[sample_names == \"a\"] → \n{data[sample_names == "a"]}')

data[sample_names == "a"] → 
[[ 1.764  0.4    0.979  2.241  1.868]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


#### 5-2-1-3

In [12]:
cond_data = np.array([True, True, False, False, True])
x_array = np.arange(1, 6)
y_array = np.arange(100, 501, 100)

np.where(cond_data, x_array, y_array)

array([  1,   2, 300, 400,   5])

***
### Practice 5-1

In [21]:
sample_names2 = np.array([i for i in 'abcda']) 
np.random.seed(0)
data2 = np.random.randn(5, 5)

print(sample_names2)
print(data2)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [23]:
data2[sample_names2 == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

***
### Practice 5-2

In [24]:
data2[sample_names2 != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

***
### Practice 5-3

In [25]:
x_array1 = np.arange(1, 6)
y_array1 = np.arange(6, 11)

np.where(np.array([False, False, True, True, False]), x_array1, y_array1) 

array([ 6,  7,  3,  4, 10])

***
### 5-2-2